print('\033[31m' + "cddddddddddddddddddddddddddddddddddddddddddd;")
print('\033[31m' + "0Mo..........':ldkO0KKXXKK0kxoc,..........kMd")
print('\033[31m' + "0Ml......;d0WMMMMMMMMMMMMMMMMMMMWKx:......kMd")
print('\033[31m' + "0Ml...cOWMMMMMMMMMMMMMMMMMMMMMMMMMMMWO:...kMd")
print('\033[31m' + "0Ml.lNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNc.kMd")
print('\033[31m' + "0MdKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0OMd")
print('\033[31m' + "0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd")
print('\033[31m' + "0MxcxWMMMMMNXXNMMMMMMMMMMMMMMMNXXNMMMMMWkcKMd")
print('\033[31m' + "0Md..lMKo,.,'...:kWMMMMMMMNx;...',.;dXMl.'XMd")
print('\033[31m' + "0Mx'.,O;dXMMMXl....:dWMNo;....oXMMMKd;0,.'KMd")
print('\033[31m' + "0MO;.,NMWMMMMMMWk;...XMK...:OWMMMMMMWMN,.cNMd")
print('\033[31m' + "0MxxNMX;KMMKdcclkWN0WMMMN0WNxc:lxXMMk;WMXdKMd")
print('\033[31m' + "0MMMMMO;MMl.......KMXOMNkMk.......xMM.NMMMMMd")
print('\033[31m' + "0MMMMMMXKoclddl;.oWMdkMN,MN:.:ldolcdXNMMMMMMd")
print('\033[31m' + "0MMMMMMWXMMMMMMMW0KdoNMMdox0MMMMMMMMXMMMMMMMd")
print('\033[31m' + "0MMMMXc'WMMMMMMMMkcWMMMMMMkcMMMMMMMMN'lXMMMMd")
print('\033[31m' + "0MMMd..cMMMMMMMMNdoKMMMMM0x:XMMMMMMMM:..kMMMd")
print('\033[31m' + "0MM0....d0KKOd:.....c0Kx'.....:d0NX0l....NMMd")
print('\033[31m' + "0MMO.....................................WMMd")
print('\033[31m' + "0Mdkc...................................0kOMd")
print('\033[31m' + "0Ml.:Ol;........';;.......;,........':oX:.kMd")
print('\033[31m' + "0Ml..,WMMMMWWWo...';;:c::;'...:WWMMMMMW;..kMd")
print('\033[31m' + "0Ml...dMMMMMMMMKl...........c0MMMMMMMMd...kMd")
print('\033[31m' + "0Ml...cMMMMMMMMMMMXOxdddk0NMMMMMMMMMMM'...kMd")
print('\033[31m' + "0Ml....KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO....kMd")
print('\033[31m' + "0Ml.....OMMMMMMMMMMMMMMMMMMMMMMMMMMMK.....kMd")
print('\033[31m' + "0Ml......:XMMMMMMMMMMMMMMMMMMMMMMMNl......kMd")
print('\033[31m' + "0Ml........lXMMMMMMMMMMMMMMMMMMMKc........kMd")
print('\033[31m' + "0Ml..........:KMMMMMMMMMMMMMMM0,..........kMd")
print('\033[31m' + "oO:............xOOOx:'';dOOOOd............lOc")
print('\033[31m' + "o0:...............FSOCIETY................:0o")
print('\n')
print('\033[39m')
print('@@@@@@@@@@@@@@@@@@@@@@@@@@@')
print('@------W-E-L-C-O-M-E------@')
print('@ Please Choose an Option @')
print('|‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾|')
print('| [1] HOME | [2] BUSINESS |')
print('|        [3] EXIT         |')
print('|_________________________|')